export const routes = {
  backIdCard: '/:id/back-id-card',
  dipChip: '/:id/dip-chip',
  criminalCheck: '/:id/criminal-check',
  employmentVerification: '/:id/employment-verification',
  dopa: '/:id/dopa',
  frontIdCard: '/:id/front-id-card',
  idFaceRecognition: '/:id/id-face-recognition',
  helpCenter: '/help-center',
  notFound: '/not-found',
  passport: '/:id/passport',
  pdpa: '/:id/privacy-policy',
  permissionError: '/permission-error',
  vaccinePassport: '/:id/vaccine-passport',
  verification: '/:id',
  verificationCompleted: '/:id/completed',
  verificationExpired: '/expired',
  feedback: '/:id/feedback',
}

export const pageTitles: Record<keyof typeof routes, string | undefined> = {
  backIdCard: 'Back ID Card',
  dipChip: 'Dip Chip',
  criminalCheck: 'Employee Check',
  employmentVerification: 'Employee Verification',
  dopa: 'Dopa',
  frontIdCard: 'Front ID Card',
  idFaceRecognition: 'ID Face Recognition',
  helpCenter: 'Help Center',
  notFound: 'Not Found',
  passport: 'Passport',
  pdpa: 'Privacy Policy',
  permissionError: 'Permission Error',
  vaccinePassport: 'Vaccine Passport', // TODO: remove
  verification: 'welcome',
  verificationCompleted: 'Verification Completed',
  verificationExpired: 'Verification Expired',
  feedback: 'Feedback',
}